// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-06-12 21:53:46.580899

library dogma_start.src.models.nx_attr_expr_def;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxAttrExprDef {
  /// Definition of the attribute expression. Example: Max(OrderID)
  String qExpression;
}
