// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-06-12 21:53:46.580899

library dogma_start.src.models.nx_measure;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'nx_attr_expr_def.dart';
import 'nx_inline_measure_def.dart';
import 'nx_value_expr.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class NxMeasure {
  /// Refers to a measure stored in the library
  @Serialize.field('qLibraryId', optional: true)
  String qLibraryId;

  /// Definition of the expression in the measure.
  ///  Example: Sum (OrderTotal)
  @Serialize.field('qDef')
  NxInlineMeasureDef qDef;
  @Serialize.field('qAttributeExpressions', optional: true)
  List<NxAttrExprDef> qAttributeExpressions;

  /// Specifies a calculation condition, which must be fulfilled for the measure
  /// to be calculated
  @Serialize.field('qCalcCond', optional: true)
  NxValueExpr qCalcCond;
}
