// Generated by Dogma Dart. DO NOT MODIFY!
// 2016-06-12 21:53:46.580899

library dogma_start.src.unmodifiable_model_views.unmodifiable_nx_attr_expr_def_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_start/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxAttrExprDef].
class UnmodifiableNxAttrExprDefView implements NxAttrExprDef {
  final NxAttrExprDef _model;

  UnmodifiableNxAttrExprDefView(this._model);

  @override
  String get qExpression => _model.qExpression;
  set qExpression(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxAttrExprDef');
  }
}
